name: JS Error Monitoring

on:
  schedule:
    # Run every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # optional: allow manual run

jobs:
  check-errors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run JS Error Monitoring
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: node check-errors.js
