name: Multi-Site Playwright Monitor

on:
  schedule:
    - cron: "*/10 * * * *" # runs every 10 minutes
  workflow_dispatch: # manual trigger

jobs:
  check-sites:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies & browsers
        run: |
          npm install playwright @sentry/node
          npx playwright install chromium   # downloads Chromium for CI

      - name: Run Playwright multi-site monitor
        run: node check-errors.js
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
